### ISSUE TITLE
Can't use bold, italic, etc.

### ISSUE THREAD

**Issue by DominicDevelop** [erincayaz/obsidian-colored-text#20]
As soon as I use a color, the text formats like bold or italic won't work anymore or I am using them wrong :(

**Comment by erincayaz** [comment]
Hi, I didn't think about this case. Because text is wrapped in HTML, Obsidian's way of making bold/italic is not working. You can add font weight to generated span temporarily: `<span style="color:#ffff11; font-weight: bold">lorem ipsum</span>` and I will try to figure out a way to make this more user friendly.

If you have any suggestion on this topic, feel free to share.

**Comment by maread99** [comment]
Isn't the only (or at least easiest) way of doing this to store 'styles' rather than colors, with a style comprising:
* color
* bold (bool)
* italic (bool)

The extra styling could perhaps be represented in the slot with 'B', 'I' or 'BI' characters appearing in the color square?

Thanks for the plugin!

**Comment by erincayaz** [comment]
@maread99 I was thinking of having 2 buttons on the status bar that represent Bold and Italic and by clicking the buttons user can activate bold and/or italic.

For storage, why did you suggest storing bold and italic for each square? I think that could be unnecessary because having one bold and italic option that affects all coloring can be enough.

Thank you for sharing!

**Comment by maread99** [comment]
> I was thinking of having 2 buttons on the status bar that represent Bold and Italic and by clicking the buttons user can activate bold and/or italic.

That would be grand.

I'm not sure what I was thinking!

Thanks again.

**Comment by erincayaz** [comment]
Hi, I made a new release that is covering this issue #27. Unfortunately, it is not fully functional yet, you need to be very precise for bold and italic to work but at least it gives a way to make the text bold/italic. Right now it only works with the shortcuts (Ctrl + B, Ctrl + I) and the whole text (including HTML elements) should be selected. 

The other cases, such as wrapping colored text by hand, removing the color, and selecting more than one text with colored text in it are not covered yet. I want to implement those as well however it is hard to do, so I want to first give a way to make colored text bold, and italic until then.

Because of these I am not closing the issue, just wanted to give an update.

**Comment by ansuhayda** [comment]
Hello!
I just installed your plugin and also noticed it removed any formatting such as bold, italics, etc. which led me to this topic.  In your last comment, you said using hotkeys will work to format the text, but I found a bug with this.  For bold, Ctrl + B, it sets the text to italics.  I tried manually changing the word from italic to bold but this did not work.  Just wanted to let you know.  Thanks!

**Comment by erincayaz** [comment]
Hello, I apologize for the late update. I took a break from the project but have now returned to resolve some issues. I’ve released a new version that addresses this issue. You can check out a brief demo here:
![output](https://github.com/user-attachments/assets/7267904c-aee5-47fb-99a8-3e7ca2cfaa87)

In the demo, I use the default bold and italic shortcuts: Ctrl+B (or CMD+B on Mac). If the selected text doesn’t already have the styling, the shortcut adds it. If it does, the shortcut removes it—just like the default Obsidian behavior.

It still need some improvements, right now this feature doesn't work if whole text is not selected, but in Obsidian if anchor is inside the text, markdown still covers the whole word. I will add it in the future but right now I see that as a small improvement so will close the issue and add it in the future.

If you have any feedback, or if you encounter any bug you can let me know,
