### ISSUE TITLE
Possible to add hotkeys shortcuts for selecting text and change the color?

### ISSUE THREAD

**Issue by KoichaDev** [erincayaz/obsidian-colored-text#23]

**Comment by erincayaz** [comment]
Hi. Can you elaborate what you mean by hotkeys for selecting texts? I am asking this because you can select text by for example: `Ctrl + Shift + ->`. Do you have another thing in mind?

Right now there are no default hotkeys for available commands but you can initialize hotkeys by going hotkeys in the settings and search for Colored Text:
![image](https://github.com/erincayaz/obsidian-colored-text/assets/45971992/41f057c0-7a26-42ae-acc4-31b3ec929206)

Is these enough for your use case?

**Comment by KoichaDev** [comment]
Yes! That hotkeys are perfect! I didn't know you could actually apply these hotkeys functionalities on the keyboard shorts! Thanks for the reply! I will close this issue 👍
